spring:
  application:
    name: cinema-service
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:cinema.db
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.SQLiteDialect
        format_sql: true
    show-sql: true

logging:
  level:
    ROOT: info
#    org.springframework: warn
#    org.springframework.security: warn
#    org.hibernate: warn
    org.hibernate.type.descriptor.sql: trace

server:
  port: 9100
eureka:
  client:
    service-url:
      registry: http://localhost:8761/registry
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream