spring:
    datasource:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite::resource:library.db
#        default-catalog: library
#        jndi-name: jdbc/Library
    jpa:
        database-platform: org.hibernate.dialect.SQLiteDialect
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                dialect: org.hibernate.dialect.SQLiteDialect
                format_sql: true
        show-sql: true


logging:
    level:
        ROOT: warn
        org.springframework: warn
        org.springframework.security: warn
        org.hibernate: warn
        org.hibernate.type.descriptor.sql: trace